apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    dag:
      tasks:
      - name: print-message-loop
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "{{item}}"
        withItems:
        - hello world
        - goodbye world

  - name: print-message
    inputs:
      parameters:
      - name: message
      - name: age
        default: 36
    container:
      image: busybox
      command: [echo]
      args: ["{{inputs.parameters.message}}-{{inputs.parameters.age}}"]